[package]
name = "flosion"
version = "0.1.0"
authors = ["timstr <timstr@cs.ubc.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"
rand = "0.8.3"
futures = "0.3"
spin_sleep = "1.0.0"
thread-priority = "0.4.1"
parking_lot = "0.11.2"
atomic_float = "0.1.0"