pub mod adsr_ui;
// pub mod melody_ui;
// pub mod sequencer_ui;
pub mod all_objects;
pub mod audioclip_ui;
pub mod definitions_ui;
pub mod ensemble_ui;
pub mod input_ui;
pub mod keyboard_ui;
pub mod mixer_ui;
pub mod oscilloscope_ui;
pub mod output_ui;
pub mod pure_function_uis;
pub mod readwritewaveform_ui;
// pub mod recorder_ui;
pub mod resampler_ui;
pub mod sampler1d_ui;
// pub mod scatter_ui;
pub mod stateful_function_uis;
pub mod wavegenerator_ui;
pub mod whitenoise_ui;
pub mod writewaveform_ui;
